[project]
name = "curso-modelacion-flujo-n-clasico"
version = "0.1.0"
description = "This project is oriented to development of Diamond Difference Algoithm to 1D neutron flux problems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "ruff>=0.14.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
